### ISSUE TITLE
Do not sort packages before installing them

### ISSUE THREAD

**Issue by vaonet-jks** [tobetter/odroid-stamper#4]
So packages can be grouped.

**Comment by tobetter** [comment]
How the packages can be grouped??

**Comment by vaonet-jks** [comment]
Assuming comments are allowed (#3), I was thinking of something like this:
```
# Network Packages
ifupdown
iptables
iputils-arping
net-tools
traceroute
# USB/Wireless Packages
usb-modeswitch
usbutils
lshw
wireless-tools
iw
```

**Comment by tobetter** [comment]
The package does not need to be sorted in the file 'packages', the package will be sorted when they are going to be installed which is actually not necessary but it does... :)

So having comment in the file 'packages' has been fixed with the patch below, please check if it meets your requirements.
https://github.com/tobetter/odroid-stamper/commit/87f3cbffbf2681822645498f628a5b2230b4bb32

**Comment by vaonet-jks** [comment]
Excellent! With a bonus `;` comment ability!

**Comment by tobetter** [comment]
So...let me close this issue. :)
